### ISSUE TITLE
wrong TR (=1.0) in header after preprocessing

### ISSUE THREAD

**Issue by jcrdubois** [adolphslab/HCP_MRI-behavior#5]
Need to investigate in more detail. Affects volumetric data only. The nifti header is wrong in the preprocessed data, with TR=1.0s [pixdim 4]. Probably an easy fix, making a note here to address.

**Comment by paola-g** [comment]
The problem is very likely happening here (line 1645, HCP_helpers.py): 

`nib.save(nib.Nifti1Image(niiImg.reshape((nRows, nCols, nSlices, nTRs), order='F').astype('<f4'), affine),op.join(outDir,outFile+'.nii.gz'))`

where we should give the header as a third parameter to the Nifti1Image function:

`Nifti1Image(dataobj, affine, header=None, extra=None, file_map=None)
`

The header could be an extra output of our load_img() function.

**Comment by jcrdubois** [comment]
Yes -- I will take a look and push a fix soon, thanks!
